dist: trusty
sudo: false
language: ruby
rvm:
  - 2.3.3
env:
  - CHROME_HEADLESS_HOST=localhost CHROME_HEADLESS_PORT=9222
services:
  - docker
before_install:
  - nvm install
  - echo $(node -v)
  - gem install bundler -v 1.16.0
  - docker pull alpeware/chrome-headless-trunk
  - docker run -d --rm -p=9222:9222 alpeware/chrome-headless-trunk
